/**
 * ID : 'suneditor_sample'
 * ClassName : 'sun-eidtor'
 */
document.addEventListener('DOMContentLoaded', function() {
    // Define plugins as an empty object or import the required plugins
    const plugins = {};

    // Create editor using the textarea ID
    const editor = SUNEDITOR.create('sample', {
        strictMode: false,
        textTags: {
          bold: "b",
          underline: "u",
          italic: "i",
          strike: "s",
        },
        mode: "balloon-always",
        rtl: false,
        fullPage: true,
        iframeCSSFileName: "http://localhost:3000",
        katex: "window.katex",
        resizingBar: false,
        showPathLabel: false,
        resizeEnable: false,
        className: "",
        defaultStyle: "",
        font: ["Arial", "tahoma", "Courier New,Courier"],
        fontSize: [8, 10, 14, 18, 24, 36],
        formats: ["p", "blockquote", "h1", "h2", "h3"],
        imageResizing: false,
        imageHeightShow: false,
        imageAlignShow: false,
        imageFileInput: false,
        imageUrlInput: false,
        videoResizing: false,
        videoHeightShow: false,
        videoAlignShow: false,
        videoFileInput: false,
        videoUrlInput: false,
        videoRatioShow: false,
        audioUrlInput: false,
        tabDisable: false,
        shortcutsHint: false,
        mediaAutoSelect: false,
        buttonList: [
          [
            "undo",
            "redo",
            "font",
            "fontSize",
            "formatBlock",
            "paragraphStyle",
            "blockquote",
            "bold",
            "underline",
            "italic",
            "strike",
            "subscript",
            "superscript",
            "fontColor",
            "hiliteColor",
            "textStyle",
            "removeFormat",
            "outdent",
            "indent",
            "align",
            "horizontalRule",
            "list",
            "lineHeight",
            "table",
            "link",
            "image",
            "video",
            "audio",
            "math",
            "imageGallery",
            "fullScreen",
            "showBlocks",
            "codeView",
            "preview",
            "print",
            "save",
            "template",
          ],
        ],
        plugins: plugins,
        codeMirror: CodeMirror,
    });
    editor.setContents("<p>This is sun editor demo for ballon always</p>");
});
